image: conanio/gcc8

stages:
  - build
  - test

build:
  stage: build
  
  before_script:
    - sudo pip install --upgrade conan
    - conan user

  script:
    - cd ./vendor/conan
    - conan install . --build missing --pr linux.txt
    - cd ../..
    - ./vendor/premake/premake5 gmake
    - make
    
test:
  image: conanio/gcc8
  stage: test

  before_script:
    - sudo pip install --upgrade conan
    - conan user
    - cd ./vendor/conan
    - conan install . --build missing --pr linux.txt
    - cd ../..
    - ./vendor/premake/premake5 gmake
    - make

  script:
    - ./build/bin/debug/tests/tests
