name: CI

on: [pull_request, push]

jobs:
  ci:
    name: ${{ matrix.name }}  
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.8]
        name: [ubuntu-18.04-gcc-9]
        include:
          - name: ubuntu-18.04-gcc-9
            os: ubuntu-18.04
            compiler: gcc
            version: "9"

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install conan
        echo "::set-env name=CC::gcc-${{ matrix.version }}"
        echo "::set-env name=CXX::g++-${{ matrix.version }}"
    - name: configure
      run: |
        mkdir build && cd build && cmake ..
    - name: build
      run: |
        cmake --build build
