name: CI

on: [pull_request, push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
  strategy:
    matrix:
      cxx: [g++-10, clang++-10]
      build_type: [Debug, Release]
      os: [ubuntu-18.04]
 
	    
    steps:  
     - uses: actions/checkout@v2
     
     - name: Make build directory
       run: cmake -E make_directory ${{runner.workspace}}/build

     - name: Configure CMake
       working-directory: ${{runner.workspace}}/build
       env:
        CXX: ${{matrix.cxx}}
       run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE 
       
     - name: Build
       working-directory: ${{runner.workspace}}/build
       run: cmake --build . --config $BUILD_TYPE

